# Form implementation generated from reading ui file 'ui_foothold_city.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FootholdCity(object):
    def setupUi(self, FootholdCity):
        FootholdCity.setObjectName("FootholdCity")
        FootholdCity.resize(966, 561)
        self.centralwidget = QtWidgets.QWidget(parent=FootholdCity)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout.addWidget(self.pushButton_open, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 2, 2, 1)
        self.graphicsView = QGraphicsViewDataVisualization(parent=self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(600, 400))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 2)
        self.pushButton_open_plot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_open_plot.setObjectName("pushButton_open_plot")
        self.gridLayout.addWidget(self.pushButton_open_plot, 1, 1, 1, 1)
        FootholdCity.setCentralWidget(self.centralwidget)

        self.retranslateUi(FootholdCity)
        QtCore.QMetaObject.connectSlotsByName(FootholdCity)

    def retranslateUi(self, FootholdCity):
        _translate = QtCore.QCoreApplication.translate
        FootholdCity.setWindowTitle(_translate("FootholdCity", "Опорный город"))
        self.pushButton_open.setText(_translate("FootholdCity", "Открыть"))
        self.pushButton_open_plot.setText(_translate("FootholdCity", "Открыть график"))
from Foothold_city.Widgets.qgraphicsview_data_vizualization import QGraphicsViewDataVisualization
